title: CleanupTools
description: Linux & Python tools for file cleanup
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: C. Reimer
repo_url: "https://github.com/CJBR-97/CleanupTools"
edit_on_github: true
github_docs_folder: true
include_homepage_in_sidebar: true
#logo: 'https://your.url/image.png'
#site_favicon: 'https://your.url/here.ico'
sticky_navigation: true
search_enabled: true
google_analytics_anonymize_ip: true
hljs_style: github-gist
prev_next_buttons_location: None
